// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: multiply-service.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NumbersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api     string  `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Number1 float32 `protobuf:"fixed32,2,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2 float32 `protobuf:"fixed32,3,opt,name=number2,proto3" json:"number2,omitempty"`
}

func (x *NumbersRequest) Reset() {
	*x = NumbersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiply_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumbersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumbersRequest) ProtoMessage() {}

func (x *NumbersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiply_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumbersRequest.ProtoReflect.Descriptor instead.
func (*NumbersRequest) Descriptor() ([]byte, []int) {
	return file_multiply_service_proto_rawDescGZIP(), []int{0}
}

func (x *NumbersRequest) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *NumbersRequest) GetNumber1() float32 {
	if x != nil {
		return x.Number1
	}
	return 0
}

func (x *NumbersRequest) GetNumber2() float32 {
	if x != nil {
		return x.Number2
	}
	return 0
}

type NumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api     string  `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Number1 float32 `protobuf:"fixed32,2,opt,name=number1,proto3" json:"number1,omitempty"`
}

func (x *NumberResponse) Reset() {
	*x = NumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiply_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberResponse) ProtoMessage() {}

func (x *NumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiply_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberResponse.ProtoReflect.Descriptor instead.
func (*NumberResponse) Descriptor() ([]byte, []int) {
	return file_multiply_service_proto_rawDescGZIP(), []int{1}
}

func (x *NumberResponse) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *NumberResponse) GetNumber1() float32 {
	if x != nil {
		return x.Number1
	}
	return 0
}

var File_multiply_service_proto protoreflect.FileDescriptor

var file_multiply_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2c, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x0e, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70,
	0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x69, 0x12, 0x18, 0x0a, 0x07,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32,
	0x22, 0x3c, 0x0a, 0x0e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x61, 0x70, 0x69, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x31, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x31, 0x32, 0x65,
	0x0a, 0x0f, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x52, 0x0a, 0x0f, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x12, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x11, 0x22, 0x0c, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x79, 0x3a, 0x01, 0x2a, 0x42, 0xe8, 0x01, 0x92, 0x41, 0xe4, 0x01, 0x12, 0x7e, 0x0a, 0x10,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x20, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x65, 0x0a, 0x18, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x6d, 0x75, 0x6c, 0x74,
	0x69, 0x70, 0x6c, 0x79, 0x20, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x30, 0x68, 0x74,
	0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x61, 0x6d, 0x75, 0x73, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x2f, 0x67, 0x6f,
	0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x1a, 0x17,
	0x64, 0x61, 0x6e, 0x69, 0x65, 0x6c, 0x2e, 0x73, 0x61, 0x6d, 0x6b, 0x69, 0x74, 0x40, 0x67, 0x6d,
	0x61, 0x69, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x32, 0x03, 0x31, 0x2e, 0x30, 0x2a, 0x01, 0x01, 0x32,
	0x10, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6a, 0x73, 0x6f,
	0x6e, 0x3a, 0x10, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6a,
	0x73, 0x6f, 0x6e, 0x52, 0x3b, 0x0a, 0x03, 0x34, 0x30, 0x34, 0x12, 0x34, 0x0a, 0x2a, 0x52, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x65, 0x64, 0x20, 0x77, 0x68, 0x65, 0x6e, 0x20, 0x74, 0x68, 0x65, 0x20,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x20, 0x64, 0x6f, 0x65, 0x73, 0x20, 0x6e, 0x6f,
	0x74, 0x20, 0x65, 0x78, 0x69, 0x73, 0x74, 0x2e, 0x12, 0x06, 0x0a, 0x04, 0x9a, 0x02, 0x01, 0x07,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_multiply_service_proto_rawDescOnce sync.Once
	file_multiply_service_proto_rawDescData = file_multiply_service_proto_rawDesc
)

func file_multiply_service_proto_rawDescGZIP() []byte {
	file_multiply_service_proto_rawDescOnce.Do(func() {
		file_multiply_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_multiply_service_proto_rawDescData)
	})
	return file_multiply_service_proto_rawDescData
}

var file_multiply_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_multiply_service_proto_goTypes = []interface{}{
	(*NumbersRequest)(nil), // 0: v1.NumbersRequest
	(*NumberResponse)(nil), // 1: v1.NumberResponse
}
var file_multiply_service_proto_depIdxs = []int32{
	0, // 0: v1.MultiplyService.MultiplyNumbers:input_type -> v1.NumbersRequest
	1, // 1: v1.MultiplyService.MultiplyNumbers:output_type -> v1.NumberResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_multiply_service_proto_init() }
func file_multiply_service_proto_init() {
	if File_multiply_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_multiply_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumbersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiply_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_multiply_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multiply_service_proto_goTypes,
		DependencyIndexes: file_multiply_service_proto_depIdxs,
		MessageInfos:      file_multiply_service_proto_msgTypes,
	}.Build()
	File_multiply_service_proto = out.File
	file_multiply_service_proto_rawDesc = nil
	file_multiply_service_proto_goTypes = nil
	file_multiply_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MultiplyServiceClient is the client API for MultiplyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MultiplyServiceClient interface {
	MultiplyNumbers(ctx context.Context, in *NumbersRequest, opts ...grpc.CallOption) (*NumberResponse, error)
}

type multiplyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiplyServiceClient(cc grpc.ClientConnInterface) MultiplyServiceClient {
	return &multiplyServiceClient{cc}
}

func (c *multiplyServiceClient) MultiplyNumbers(ctx context.Context, in *NumbersRequest, opts ...grpc.CallOption) (*NumberResponse, error) {
	out := new(NumberResponse)
	err := c.cc.Invoke(ctx, "/v1.MultiplyService/MultiplyNumbers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiplyServiceServer is the server API for MultiplyService service.
type MultiplyServiceServer interface {
	MultiplyNumbers(context.Context, *NumbersRequest) (*NumberResponse, error)
}

// UnimplementedMultiplyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMultiplyServiceServer struct {
}

func (*UnimplementedMultiplyServiceServer) MultiplyNumbers(context.Context, *NumbersRequest) (*NumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiplyNumbers not implemented")
}

func RegisterMultiplyServiceServer(s *grpc.Server, srv MultiplyServiceServer) {
	s.RegisterService(&_MultiplyService_serviceDesc, srv)
}

func _MultiplyService_MultiplyNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiplyServiceServer).MultiplyNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MultiplyService/MultiplyNumbers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiplyServiceServer).MultiplyNumbers(ctx, req.(*NumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MultiplyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.MultiplyService",
	HandlerType: (*MultiplyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MultiplyNumbers",
			Handler:    _MultiplyService_MultiplyNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multiply-service.proto",
}
